version: 2.1

jobs:
  test:
    working_directory: ~/secondProject
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py

workflows:
  build:
    jobs:
      - test
     
