version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 Test.py
  build_test:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - run:
          name: Trigger the Build Job
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/github/Kamsapphire/FirstProject/pipeline' \
            --header 'Content-Type: application/json' \
            -u "{$API_TOKEN}"
